services:
  school-system-database:
    container_name: school-system-database-pg
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${SCHOOL_SYSTEM_DB_USER}
      POSTGRES_PASSWORD: ${SCHOOL_SYSTEM_DB_PASSWORD}
      POSTGRES_DB: ${SCHOOL_SYSTEM_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${SCHOOL_SYSTEM_DB_EXTERNAL_PORT}:5432"
    volumes:
      - school-system-data:/var/lib/postgresql/data
    networks:
      - school-system-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SCHOOL_SYSTEM_DB_USER} -d ${SCHOOL_SYSTEM_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  school-system-api:
    build:
      context: .
      dockerfile: apps/school-system/Dockerfile
    image: school-system-img
    container_name: school-system-api
    ports:
      - "${SCHOOL_SYSTEM_PORT}:3000"
    env_file:
      - .env
    environment:
      - APP_NAME=school-system
    depends_on:
      school-system-database:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/usr/src/app/entrypoint.sh"]
    networks:
      - school-system-network
      - network-microservices
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  service-notes-database:
    container_name: service-notes-database-pg
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${SERVICE_NOTES_DB_USER}
      POSTGRES_PASSWORD: ${SERVICE_NOTES_DB_PASSWORD}
      POSTGRES_DB: ${SERVICE_NOTES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${SERVICE_NOTES_DB_EXTERNAL_PORT}:5432"
    volumes:
      - service-notes-data:/var/lib/postgresql/data
    networks:
      - service-notes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SERVICE_NOTES_DB_USER} -d ${SERVICE_NOTES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  service-notes-api:
    build:
      context: .
      dockerfile: apps/service-notes/Dockerfile
    image: service-notes-img
    container_name: service-notes-api
    ports:
      - "${SERVICE_NOTES_PORT}:3000"
    env_file:
      - .env
    environment:
      - APP_NAME=service-notes
    depends_on:
      service-notes-database:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/usr/src/app/entrypoint.sh"]
    networks:
      - service-notes-network
      - network-microservices
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

# ... (networks e volumes permanecem iguais)
networks:
  school-system-network:
    driver: bridge
  service-notes-network:
    driver: bridge
  network-microservices:
    driver: bridge

volumes:
  school-system-data:
  service-notes-data: